spring:
  datasource:
    url: jdbc:mysql://localhost:3306/educational
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wen1106.

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #??
    suffix: .html #????
#    mode: HTML #??


#??mybatis
mybatis:
  type-aliases-package: com.example.edu.entity
  mapper-locations: classpath:mybatis/mapper/*.xml